#%RAML 1.0
---

title: Check a UK EORI Number
description: Check if an EORI number beginning with GB (issued by the UK) is valid and retrieve an associated business name and address (if the business agreed to share this information).
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Testing
    content: !include docs/testing.md

#TODO update url
/customs/eori/lookup:
    /check-multiple-eori:
      post:
        displayName: Check multiple eori numbers
        description: !include docs/check-multiple-eoris-post.md
        is: [headers.acceptHeader, headers.contentHeader]
        body:
          application/json:
            type: !include schemas/post-multiple-eoris.json
            examples:
              example-1:
                description: "Check multiple EORI Numbers example"
                value: !include examples/post-multiple-eoris-request-example-1.json
        responses:
          200:
            body:
              application/json:
                examples:
                 example-1:
                  description: "Check multiple EORI Numbers example"
                  value: !include examples/post-mulitple-eoris-response-example-1.json
          400:
            body:
              application/json:
                schema: !include "schemas/error.json"
                description: Invalid request
                example: |
                  {
                    "code": "INVALID_REQUEST",
                    "message": "Invalid eori - eori parameters should be between 12 or 15 digits"
                  }
          500:
            body:
              application/json:
                schema: !include "schemas/error.json"
                description: Internal server error
                example: |
                  {
                    "code": "INTERNAL_SERVER_ERROR",
                    "message": "Unknown error"
                  }
